### ISSUE TITLE
Env creation fails

### ISSUE THREAD

**Issue by riturajtiwari** [udacity/fcnd-issue-reports#22]
Per instructions under "Environment Setup", when I run:
$ conda env create -f environment.yml

I get the following failure. Oddly, the build is declared a success and I am able to move forward: 

Building wheels for collected packages: pymavlink
  Running setup.py bdist_wheel for pymavlink ... error
  Complete output from command /Users/rituraj_tiwari/miniconda3/envs/fcnd/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/dk/_z6m0q_d7c3315fbk7kgtqn80000gn/T/pip-build-p9pzec61/pymavlink/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/dk/_z6m0q_d7c3315fbk7kgtqn80000gn/T/tmp6e0v91mtpip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/dk/_z6m0q_d7c3315fbk7kgtqn80000gn/T/pip-build-p9pzec61/pymavlink/setup.py", line 160, in <module>
      ext_modules = extensions
    File "/Users/rituraj_tiwari/miniconda3/envs/fcnd/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/Users/rituraj_tiwari/miniconda3/envs/fcnd/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/Users/rituraj_tiwari/miniconda3/envs/fcnd/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/Users/rituraj_tiwari/miniconda3/envs/fcnd/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/Users/rituraj_tiwari/miniconda3/envs/fcnd/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 204, in run
      self.run_command('build')
    File "/Users/rituraj_tiwari/miniconda3/envs/fcnd/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Users/rituraj_tiwari/miniconda3/envs/fcnd/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/Users/rituraj_tiwari/miniconda3/envs/fcnd/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/Users/rituraj_tiwari/miniconda3/envs/fcnd/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Users/rituraj_tiwari/miniconda3/envs/fcnd/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/private/var/folders/dk/_z6m0q_d7c3315fbk7kgtqn80000gn/T/pip-build-p9pzec61/pymavlink/setup.py", line 93, in run
      generate_content()
    File "/private/var/folders/dk/_z6m0q_d7c3315fbk7kgtqn80000gn/T/pip-build-p9pzec61/pymavlink/setup.py", line 21, in generate_content
      from generator import mavgen, mavparse
    File "/private/var/folders/dk/_z6m0q_d7c3315fbk7kgtqn80000gn/T/pip-build-p9pzec61/pymavlink/generator/mavgen.py", line 12, in <module>
      from future import standard_library
  ModuleNotFoundError: No module named 'future'

  ----------------------------------------
  Failed building wheel for pymavlink
  Running setup.py clean for pymavlink
Failed to build pymavlink
Installing collected packages: future, lxml, pymavlink, utm, websockets, uvloop, udacidrone
  Running setup.py install for pymavlink ... done
  Running setup.py install for udacidrone ... done
Successfully installed future-0.16.0 lxml-4.1.1 pymavlink-2.2.8 udacidrone-0.1.0 utm-0.4.2 uvloop-0.9.1 websockets-4.0.1

**Comment by riturajtiwari** [comment]
Any chance this is related to issue #17?

**Comment by jtuckerdunn** [comment]
Yes this is the same as issue #17
